### ISSUE TITLE
Wrong CNX Logo used on legacy site

### ISSUE THREAD

**Issue by pumazi** [Connexions/cnx-deploy#109]
## Summary

The wrong logo image is in use on the default setup of a legacy site. Either this needs programmatically fixed or steps need to be written that illustrate how to update it.
## Environment

all

**Comment by pumazi** [comment]
The logo is currently being updated as part of other work. The process used to do that update might be available/documented in the related [trello card](https://trello.com/c/irvrvAlf/494-change-cnx-logo-on-legacy-cnx-org).

**Comment by reedstrm** [comment]
yup, should probably do a PR against CNXPloneSite (I think) to replace the logo with whatever I'm finally handed.
