### ISSUE TITLE
Missing widgets on legacy site

### ISSUE THREAD

**Issue by pumazi** [Connexions/cnx-deploy#110]
## Summary

Production has the following widgets:

> ![screen shot 2016-10-10 at 20 32 13](https://cloud.githubusercontent.com/assets/168470/19257989/139b5c36-8f29-11e6-8e73-4d6cdf0d95f6.png)

And, for example dev00 has none:

> ![screen shot 2016-10-10 at 20 34 23](https://cloud.githubusercontent.com/assets/168470/19257995/1df96ba0-8f29-11e6-8341-a356dccb50cd.png)

Either we need to programmatically add these widgets or we need instructions illustrating how to add them to the site.
## Environment

all

**Comment by reedstrm** [comment]
ISTR this is all controlled by portlets that are in place, but look for content in specific top level folders, like `news`, `featured-content`, `announcements`, and `major-annoucement`. The front page is rendered by from `CNXPloneSite/skins/CNXPloneSite/index_html.pt` That calls portlet macros with hard-coded (relative) paths. If there's nothing in those folders, nothing is shown.

**Comment by pumazi** [comment]
This is now moot due to the work that will happen in #142.
