### ISSUE TITLE
New Template for Issues

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx-deploy#119]
For testing of CNX Deployment Phase One, suggest:

_Where are you testing?_ 
- [ ] legacy-prod00.cnx.org
- [ ] prod00.cnx.org
- [ ] legacy-staging00.cnx.org
- [ ] staging00.cnx.org...

_If testing on (legacy-)prod00.cnx.org, have you reproduced on (legacy-)staging00.cnx.org?_
- [ ] Yes
- [ ] No

_Have you tested on (legacy.)cnx.org?_
- [ ] Yes, and the behavior is different (if so, describe what's different below)
- [ ] Yes, and the behavior is the same.
- [ ] No, I have not tested there.

_What is the behavior on (legacy.)cnx.org?_
...describe...

**Comment by pumazi** [comment]
We seem to have gotten by without this... 😕
