### ISSUE TITLE
Configure varnish runtime (systemd config) fails

### ISSUE THREAD

**Issue by karenc** [Connexions/cnx-deploy#13]
## Summary

```
TASK [configure varnish runtime (systemd config)] ******************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Destination /etc/systemd/system/multi-user.target.wants/varnish.service does not exist !", "rc": 257}
```

```
$ ls -l /etc/systemd/system/multi-user.target.wants/
total 0
lrwxrwxrwx 1 root root 31 Dec 27 15:47 atd.service -> /lib/systemd/system/atd.service
lrwxrwxrwx 1 root root 33 Feb 18 18:33 nginx.service -> /lib/systemd/system/nginx.service
lrwxrwxrwx 1 root root 35 Dec 27 15:38 rsyslog.service -> /lib/systemd/system/rsyslog.service
lrwxrwxrwx 1 root root 31 Dec 27 15:47 ssh.service -> /lib/systemd/system/ssh.service
```

## Environment

local, ubuntu 14.04.3

**Comment by pumazi** [comment]
Perhaps this is Ubuntu 14.04 specific?

**Comment by reedstrm** [comment]
That looks like the list on a 14.0.4 instance that does not have varnish installed ...

**Comment by karenc** [comment]
varnish is installed, `/lib/systemd/system/varnish.service` exists.

I'll create a step that creates the symlink if it doesn't exist I guess.

**Comment by reedstrm** [comment]
weird. All the 14.0.4 instances I can reach hat have varnish installed seem to have the symlink in place.

**Comment by pumazi** [comment]
Here is what I've got. Looks like the last time I provisioned from scratch was late on the 28th of January.

```
ubuntu@local:/lib/systemd/system$ ls -la /etc/systemd/system/multi-user.target.wants
total 8
drwxr-xr-x 2 root root 4096 Jan 28 21:39 .
drwxr-xr-x 4 root root 4096 Jan 29 21:05 ..
...
lrwxrwxrwx 1 root root   38 Jan 28 21:39 varnishlog.service -> /lib/systemd/system/varnishlog.service
lrwxrwxrwx 1 root root   39 Jan 28 21:39 varnishncsa.service -> /lib/systemd/system/varnishncsa.service
lrwxrwxrwx 1 root root   35 Jan 28 21:39 varnish.service -> /lib/systemd/system/varnish.service
```

**Comment by reedstrm** [comment]
If I'm reading this correctly, we've got code in there that edits those files? That seems wrong. Shouldn't we be replacing the symlink with a copy of the system-provided file from /lib/systemd/system, and then editing it?

**Comment by pumazi** [comment]
@reedstrm That sounds like a good idea. And it would resolve the FIXME that is there. But that doesn't seem to be the issue here.

@karenc Can you verify which version of varnish is installed?

```
ubuntu@local:/lib/systemd/system$ varnishd -V
varnishd (varnish-4.0.3 revision b8c4a34)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2014 Varnish Software AS
```

**Comment by karenc** [comment]
```
karen@trusty-clean:~/cnx-deploy$ varnishd -V
varnishd (varnish-4.0.3 revision b8c4a34)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2014 Varnish Software AS
```

**Comment by reedstrm** [comment]
@pumazi yeah, just tracing through, trying to find what usually creates those symlinks.

**Comment by karenc** [comment]
I tried again with a fresh ubuntu trusty install and the symlink is still missing.

I looked at how the symlink was created for `/etc/systemd/system/multi-user.target.wants/ssh.service`.  It's from the `openssh-server` package, I believe it's from `control.tar.gz` `postinst` script:

```
$ grep -C 1 service postinst
           deb-systemd-helper debian-installed ssh.socket && \
           deb-systemd-helper --quiet was-enabled ssh.service && \
           deb-systemd-helper --quiet was-enabled ssh.socket; then
            # 1:6.5p1-1 mistakenly left both ssh.service and ssh.socket
            # enabled.
--
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask ssh.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled ssh.service; then
        # Enables the unit on first installation, creates new
        # symlinks on upgrades if the unit file has changed.
        deb-systemd-helper enable ssh.service >/dev/null || true
else
--
        # cleaned up on purge. Also remove old symlinks.
        deb-systemd-helper update-state ssh.service >/dev/null || true
fi
```

Looking at the varnish (4.0) package (from repo.varnish-cache.org), I don't think there is anything in `postinst` to create the symlink.

@pumazi Can you verify that the symlink is missing when you use ubuntu trusty?  Or I can just add a step to either create the symlink or maybe copy `/lib/systemd/system/varnish.service` and modify it instead of symlinking it.

**Comment by pumazi** [comment]
Ah... So it sounds like the varnish package differs from the one in Ubuntu 15.10.

**Comment by karenc** [comment]
Yes, most likely it's something that the ubuntu / debian package maintainers added. 

I'll add a BBB step to add the symlink then. :stuck_out_tongue:

**Comment by reedstrm** [comment]
Ah I missed that we're installing varnish from varnish-cache.org. Why? Should we use the distro packaged one?

**Comment by karenc** [comment]
@pumazi Sorry misread what you typed, the varnish package we're using for Ubuntu 14.04 is from varnish, not from ubuntu.  It's possible that Ubuntu 15.10 varnish package creates the symlink.

@reedstrm It's because we've written everything to work with varnish 4 and the Ubuntu 14.04 varnish package is too old.

**Comment by reedstrm** [comment]
Ah the usual need, newer version than what's in LTS, or backports. Carry on then. :-)
