### ISSUE TITLE
Slow prod00

### ISSUE THREAD

**Issue by oscryan** [Connexions/cnx-deploy#138]
## Summary

All attempted actions (login, module checkout, module edit/save, module publish), take even longer than on legacy.cnx.org, sometimes over a minute.

## Environment

prod

**Comment by pumazi** [comment]
There shouldn't be any difference. The same backends are being connected to. There is no caching done when one is logged in; so there shouldn't be a difference from that side of things either.

We unfortunately don't have metrics for requests times (something I hope to resolve in the future). Is there any chance you can semi-accurately measure the requests? One way to do that would be using the browser's developer tools' networking tab.

It's possible that your client has cached some of the resources on legacy.cnx.org and has yet to do that for legacy-staging00.cnx.org.

**Comment by pumazi** [comment]
I was just using the "Timeline" feature of chrome's developer tools. Some results I pulled up for comparing:
 - http://legacy.cnx.org/:
   
   ![legacy cnx org](https://cloud.githubusercontent.com/assets/168470/20015870/69cdc4a4-a27a-11e6-913f-f7a6d250e742.png)
 - http://legacy-prod00.cnx.org/:
   
   ![legacy-prod00 cnx org](https://cloud.githubusercontent.com/assets/168470/20015869/69cd8eda-a27a-11e6-8045-1efb33c28506.png)

I'm not sure what this means just yet...

**Comment by pumazi** [comment]
I hear through the grapevine that this is no longer a fuzzy issue. Reopen if you believe this to be in error.
