### ISSUE TITLE
Missing Zope data

### ISSUE THREAD

**Issue by pumazi** [Connexions/cnx-deploy#142]
## Summary

The zope site is missing data (e.g. widgets special pages, lenses). We likely need to invest in the ability to copy the `Data.fs` from production to a server.

## Environment

all

**Comment by reedstrm** [comment]
No we do not want to copy the production Data.fs: there's waaaaay to much cruft in there. There's probably a lot of TTW overrides of various templates and things that were originally done for expediency's sake, which could probably be rolled into actual code changes.

**Comment by pumazi** [comment]
Turns out that we will need to copy the production Data.fs for deployment of the zope bits to production. This won't be something we use all the time. It will likely be something we occasionally update in the `staging` environment, but not in the `dev` environment.

Because of this, we no longer need to address #110.
