### ISSUE TITLE
High School Physics Tutor exercise expansion rendering math incorrectly.

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-deploy#154]
## Summary

Math in HS Physics is displaying incorrectly in expanded Tutor problems. Per @reedstrm this is because there is "no mathmlcloud setting on dev00 in /etc/cnx/publishing/app.ini"

## Environment

Dev00 (Specifically https://dev00.cnx.org/contents/2_3FQXUs@2.1:HSbtQBUu@2/14The-Language-of-Physics-Phys)

## Screenshot
![image](https://cloud.githubusercontent.com/assets/12678235/20727419/08628cbc-b63f-11e6-97b7-d9afb72c77b0.png)

**Comment by reedstrm** [comment]
need a setting in app.ini for mathmlcloud.url as in development.ini:

mathmlcloud.url = 'http://mathmlcloud.cnx.org:1337/equation'

Probably needs to be configurable :-)
