### ISSUE TITLE
PDFs will not generate (Prod00)

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-deploy#160]
## Summary

Every time I try to regenerate (enqueue) https://legacy.cnx.org/content/col12098/latest it fails. It won't create the PDF. Here is a screencap of what is in query_ptool: 

<img width="511" alt="screen shot 2016-12-02 at 12 31 49 pm" src="https://cloud.githubusercontent.com/assets/12631203/20845567/547a6748-b88b-11e6-929f-c879dd27ba2c.png">

## Environment

production and prod

**Comment by openstaxalina** [comment]
@brittweinstein can you generate this PDF successfully on legacy.cnx.org (not the test server)?

**Comment by openstaxalina** [comment]
col12098 is a derived copy with LaTeX parameters and it also fails on the "real" legacy.cnx.org.  So this is not a legitimate regression.

However, @brittweinstein has tried to generate other PDFs and all have failed.  This is not normal.  We generate PDFs of our books all the time (for example, earlier this week before we released _Prealgebra_).  @brittweinstein is going to put more info in this issue on Monday.

**Comment by brittweinstein** [comment]
The derived copy that will not generate: https://legacy.cnx.org/content/col12098/latest/

The unique collection (1 module) that will not generate: https://legacy.cnx.org/content/col12099/latest

**Comment by pumazi** [comment]
@brittweinstein will be rolling back some content related to this issue.

@reedstrm is looking into the logs on the server. Reassigning to @reedstrm, as he is the most knowledgeable person for this part of the legacy codebase.

**Comment by pumazi** [comment]
Resolved. This was deemed to be a production issue (outside the scope of cnx-deploy).
