### ISSUE TITLE
Astronomy Shrunken Content

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-deploy#218]
## Summary

Downloaded from https://legacy-staging.cnx.org/content/col11992/latest/printinfo, content images are smaller (possibly due to larger margins): 
<img width="539" alt="screen shot 2017-02-08 at 10 45 42 am" src="https://cloud.githubusercontent.com/assets/12631203/22747157/d804e7ba-edeb-11e6-82bf-b383bce16f2e.png">

## Environment
 Downloaded from https://legacy-staging.cnx.org/content/col11992/latest/printinfo

**Comment by pumazi** [comment]
We should probably get someone textbook team to chime in on this. @helenemccarron  @InconceivableVizzini any idea what might be causing this?

**Comment by reedstrm** [comment]
Are both comparision PDFs made w/ prince11? Also, the corner marks are classic printers crop marks - there must be some prince setting that generates those:
https://www.princexml.com/doc/properties/marks/

**Comment by helenemccarron** [comment]
There are two templates for Astronomy, Astronomy Print. It looks like it's using the wrong one.

**Comment by openstaxalina** [comment]
We need both templates to work so that we can send books with the full-bleed (I think that's the term) to the printer.  @brittweinstein maybe @oscryan could give direct you to the latest PDF generated and sent to printer with Astronomy Print template?

**Comment by reedstrm** [comment]
Ah that explains the printers crop marks. :-)

**Comment by brittweinstein** [comment]
Matches the template on Prod--not an issue, closing.
