### ISSUE TITLE
Import Issues on legacy-staging.cnx.org

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-deploy#222]
**I run into the following error when I try to import a .doc file:** 

![screen shot 2017-02-13 at 3 32 25 pm](https://cloud.githubusercontent.com/assets/12631203/22904407/028f96fa-f202-11e6-83db-2964d3104b7b.png)

**When I try to import a .zip file, it appears to go through then nothing is in the editor:** 
![screen shot 2017-02-13 at 3 34 17 pm](https://cloud.githubusercontent.com/assets/12631203/22904421/14f6f7f2-f202-11e6-85cd-9764fb50c1b5.png)

**Comment by pumazi** [comment]
An install of openoffice would be the required element to make this happen. I don't think we have that installed at this time. 😖

**Comment by reedstrm** [comment]
libreoffice would be preferred. One thing about import, it happens on whichever frontend you hit, so each frontend hosting machine needs this config.

**Comment by reedstrm** [comment]
The zip import is not related to libreoffice issues though, there's no conversion on hat - it should just be iputting image files and index.cnxml file in place.

**Comment by pumazi** [comment]
@brittweinstein Can you attach the zip file you used and/or upload it to the #cnx-deploy slack channel?

**Comment by brittweinstein** [comment]
[Archive.zip](https://github.com/Connexions/cnx-deploy/files/778050/Archive.zip) @pumazi it's just a .zip of two screenshots.

**Comment by pumazi** [comment]
@brittweinstein Okay, so it's a zip of two resource files without content. Do the files show up in the "Files" tab of the editor UI?

**Comment by brittweinstein** [comment]
@pumazi yep, they do appear there! This may not be an issue in that case. The .docx file is there as well.

**Comment by pumazi** [comment]
Excellent. We'll consider the zip import a non-issue. The .doc import is still an issue since we now know that an office product is not installed on the servers. Work is underway to resolve the .doc import.

**Comment by reedstrm** [comment]
agreed, zip did what it was supposed to.

**Comment by dtwilliamson** [comment]
xvfb will need to be installed for use by lowriter (libreoffice)

**Comment by dtwilliamson** [comment]
/var/lib/cnx/cnx-buildout/scripts/oolaunch

needs double-hyphen options for lowriter (single-hyphen options work, but they cause deprecation messages to be issued)

`$OOWRITER --headless "--accept=socket,host=localhost,port=2002;urp;" --display :1.0 &`

**Comment by reedstrm** [comment]
To fix the actual install we need to do 3 things:
- install LibreOffice 4.1 (last one w/ sxw export that I could find)
    - https://downloadarchive.documentfoundation.org/libreoffice/old/4.1.6.2/deb/x86_64/LibreOffice_4.1.6.2_Linux_x86-64_deb.tar.gz
  - untar, install all debs in DEBS subfolder (installs to /opt/libreoffice4.1)

 - remove the `--display` and Xvfb server (not needed anymore) from oolaunch, and switch path to /opt/libreoffice4.1/program/swriter
 - install unoconv - our own copy, tweaked to use /opt/libreoffice4.1/program/python
 - gut ooconvert, call `unoconv --stream` under the hood.

**Comment by reedstrm** [comment]
bullets 2-4 above are taken car of by https://github.com/Rhaptos/cnx-buildout/pull/23

**Comment by DarkPrinceFrost** [comment]
Just to confirm then, the only task that remains is:
**Instal LibreOffice4.1 via `tar` and install packages with `dpkg` located in the `DEBS` folder of the unpacked archive**
