### ISSUE TITLE
Latex PDF generation failed on legacy-staging.cnx

### ISSUE THREAD

**Issue by Bkblodget** [Connexions/cnx-deploy#227]
## Summary
Generation of col10040 failure. 
## Environment
<img width="1378" alt="screen shot 2017-02-15 at 12 54 52 pm" src="https://cloud.githubusercontent.com/assets/11299035/22997382/c648672a-f397-11e6-9233-2e73987bcd67.png">

**Comment by DarkPrinceFrost** [comment]
I don't think this is related to latex since I see the same latex failures on the older servers. Errors from legacy-frontend6 for col10040
```
/tmp/colprint_col10040.stderr:!!! Error: Writing to gs failed, error code 1                               
/tmp/colprint_col10040.stderr:!!! Error: Writing to gs failed, error code 1                               
/tmp/colprint_col10040.stdout:Failed to create the collection LaTeX zip.
```

Errors on staging06 for col10040
```
/tmp/colprint_col10040.stderr:!!! Error: Writing to gs failed, error code 1                               
/tmp/colprint_col10040.stderr:!!! Error: Writing to gs failed, error code 1                               
/tmp/colprint_col10040.stderr:mktexpk: /usr/share/texlive/texmf-dist/web2c/mktexdir ./.texmf-var/fonts/pk/ljfour/jknappen/ec failed.                                                                                 
/tmp/colprint_col10040.stderr:mktexpk: /usr/share/texlive/texmf-dist/web2c/mktexdir ./.texmf-var/fonts/pk/ljfour/jknappen/ec failed.                                                                                 
/tmp/colprint_col10040.stderr:mktexpk: /usr/share/texlive/texmf-dist/web2c/mktexdir ./.texmf-var/fonts/pk/ljfour/jknappen/ec failed.                                                                                 
/tmp/colprint_col10040.stdout:Makefile:33: recipe for target 'col10040.pdf' failed                        
/tmp/colprint_col10040.stdout:Makefile:33: recipe for target 'col10040.pdf' failed                        
/tmp/colprint_col10040.stdout:Makefile:33: recipe for target 'col10040.pdf' failed                        
/tmp/colprint_col10040.stdout:Makefile:33: recipe for target 'col10040.pdf' failed                        
/tmp/colprint_col10040.stdout:Failed to create the collection PDF.                                        
/tmp/colprint_col10040.stdout:Failed to create the collection LaTeX zip.
```

Additionally:
```
kpathsea: Running mktexpk --mfmode / --bdpi 600 --mag 1+0/600 --dpi 600 ectt0900                          
mktexpk: /usr/share/texlive/texmf-dist/web2c/mktexdir ./.texmf-var/fonts/pk/ljfour/jknappen/ec failed.    
kpathsea: Appending font creation commands to missfont.log.                                               
make: [col10040.pdf] Error 1 (ignored)               
make: [col10040.pdf] Error 2 (ignored)               

kpathsea: Running mktexpk --mfmode / --bdpi 600 --mag 1+0/600 --dpi 600 ectt0900                          
mktexpk: /usr/share/texlive/texmf-dist/web2c/mktexdir ./.texmf-var/fonts/pk/ljfour/jknappen/ec failed.    
kpathsea: Appending font creation commands to missfont.log.                                               
make: [col10040.pdf] Error 1 (ignored)               

kpathsea: Running mktexpk --mfmode / --bdpi 600 --mag 1+0/600 --dpi 600 ectt0900                          
mktexpk: /usr/share/texlive/texmf-dist/web2c/mktexdir ./.texmf-var/fonts/pk/ljfour/jknappen/ec failed.    
kpathsea: Appending font creation commands to missfont.log.                                               
make: [col10040.pdf] Error 1 (ignored)
```

**Comment by Bkblodget** [comment]
I'm not sure how relevant this is, but I was able to successfully generate this collection on production yesterday:
<img width="1229" alt="screen shot 2017-02-16 at 2 31 07 pm" src="https://cloud.githubusercontent.com/assets/11299035/23039861/bf2fbeda-f454-11e6-9257-dd4ef65fd710.png">

**Comment by pumazi** [comment]
We are going to attempt to repeat this failure on dev. If successfully repeated, @DarkPrinceFrost is going to manually deploy the fonts to dev. If that works we'll go about making the adjustment to cnx-deploy.

The good news is that @DarkPrinceFrost already has these fonts zipped up.

**Comment by DarkPrinceFrost** [comment]
1. Installed all missing fonts
2. Installed any additional font packages present on old server
3. Verified all latex packages installed
4. Manually ran the `mktexpk --mfmode / --bdpi 600 --mag 1+0/600 --dpi 600 ectt0900` command

**Comment by DarkPrinceFrost** [comment]
colprint_10040.stderr and colcomplete_10040.stderr have errors where the old server doesn't
Traceback (most recent call last):
  File "content2epub.py", line 145, in ?
    sys.exit(main())
  File "content2epub.py", line 128, in main
    dbk, newFiles = collection2dbk.convert(p, collxml, modulesDict, temp_dir, svg2png=True, math2svg=True, reduce_quality=args.reduce_quality)
  File "/var/lib/cnx/cnx-buildout/eggs/Products.RhaptosPrint-0.96-py2.4.egg/Products/RhaptosPrint/epub/collection2dbk.py", line 70, in convert
    modDbk, newFilesMod = module2dbk.convert(module, cnxml, filesDict, collParams, module_temp_dir, svg2png, math2svg, reduce_quality)
  File "/var/lib/cnx/cnx-buildout/eggs/Products.RhaptosPrint-0.96-py2.4.egg/Products/RhaptosPrint/epub/module2dbk.py", line 402, in convert
    xml, newFiles2, errors = transform(xml, origAndNewFiles, **params)
  File "/var/lib/cnx/cnx-buildout/eggs/Products.RhaptosPrint-0.96-py2.4.egg/Products/RhaptosPrint/epub/module2dbk.py", line 293, in mathml2svg
    raise ValueError("returned mathml not expected")
ValueError: returned mathml not expected

**Comment by pumazi** [comment]
We believe we're able to correct the issue with a combination of the font file addition, latex package install, 8d8db8e4022c6ac04194476091d0145d55f75c58 and Rhaptos/cnx-buildout/pull/22.

**Comment by pumazi** [comment]
Turns out we already have the latex packages installed. The fonts have been taken care of in #230.

**Comment by pumazi** [comment]
We believe this is resolved. We've successfully build `col10040/1.8` on dev and staging environments.

@Bkblodget Feel free to re-open this issue if you run into latex pdf problems when you continue testing.
