### ISSUE TITLE
Slow URL Command response

### ISSUE THREAD

**Issue by Bkblodget** [Connexions/cnx-deploy#233]
## Summary

When inputting URL commands legacy-staging.cnx is very slow to respond, taking anywhere from 2-7 minutes to return results. 

Commands used: 
latest/printinfo
latest/query_ptool
/queue_tool/pending_count

## Environment

legacy-staging.cnx.org

**Comment by pumazi** [comment]
I'm not seeing any slowness when directly accessing the zclient (zope front-end) for these URLs. I've also accessed them indirectly (through the caching service) to find that it actually seem quite snappy on both dev and staging. I tried collections 11406, 11778 and 10040.

@Bkblodget I'm unable to reproduce the slowness you speak of... Maybe @brittweinstein could also inspect?

**Comment by DarkPrinceFrost** [comment]
I'm thinking that if people were testing on Friday, then they would most definitely would have encountered issues since we were actively making modifications and restarting services.

**Comment by pumazi** [comment]
I'm fairly certain this has been resolved. Feel free to reopen if you believe it is still an issue.
