### ISSUE TITLE
PDF generation by download fails on legacy staging

### ISSUE THREAD

**Issue by karenc** [Connexions/cnx-deploy#353]
## Summary

It should be possible to trigger PDF generation by clicking the download link on the zope site.  On staging, it is returning "PDFLatexError":

```
2017-08-02T12:29:39 ERROR Zope.SiteErrorLog http://legacy-staging.cnx.org/content/m10864/2.3/index_html
Traceback (innermost last):
  Module ZPublisher.Publish, line 115, in publish
  Module ZPublisher.mapply, line 88, in mapply
  Module ZPublisher.Publish, line 41, in call_object
  Module Products.RhaptosModuleStorage.ModuleView, line 156, in index_html
  Module Products.RhaptosModuleStorage.ModuleView, line 484, in default
  Module Products.RhaptosModuleStorage.ModuleView, line 629, in downloadPDF
  Module Products.RhaptosPDFLatexTool.PDFLatexTool, line 142, in convertFSDirToPDF
PDFLatexError: No output file
```

Looking at PDFLatexTool, I think it is trying to generate the PDF file without enqueuing it.  There are packages that are only installed on the pdf_gen servers, not on the zclient servers.  This is probably the reason why we are seeing this failure.

## Environment

staging (affects all environments where zclients and pdf_gen are on different servers)

**Comment by edwoodward** [comment]
This same issue is possibly on production. Selecting random modules and attempting to download PDFs consistently results in a PDFLatexError

**Comment by kajalp** [comment]
when do we plan on fixing this? Would this be a book-tools thing?

**Comment by karenc** [comment]
We deployed [v2.1.3](https://github.com/Connexions/cnx-deploy/commits/v2.1.3) to staging and I was able to generate a PDF by clicking on the download link.

**Comment by kerwinso** [comment]
I also got a module PDF to download fine on legacy-staging.cnx.org.

Although this fix wasn't deployed to the other instances (legacy-staging 1 through 5), I tested those too and module PDF downloads work fine.
