### ISSUE TITLE
restarting workers don't always find their queues

### ISSUE THREAD

**Issue by reedstrm** [Connexions/cnx-deploy#376]
https://github.com/Connexions/cnx-deploy/blob/d25c0da2bd1dd3c2bcfc50ece62a086ea566e8a6/roles/publishing_worker/templates/etc/supervisor/conf.d/publishing_celery_workers.conf#L4

Given the weird failure-to-connect-on-restart Kerwin and I experienced when trying to test the queue, do we want to consider adding `-Q default -Q deferred` to the worker startup line? That seemed to be a reliable workaround for similar problems I found online

**Comment by karenc** [comment]
Fixed in #394 and #402.
