### ISSUE TITLE
legacy PDFs not building on staging.cnx.org

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-deploy#381]
For future staging deployments (not required for Assignable Webview project release):

Per Ross, the printhost url (`downloadhost` in RhaptosPrint) isn't set correctly -- it's pointing at production. This is causing PDFs enqueued on staging to fail (e.g., http://legacy-staging.cnx.org/content/col23622/latest/printinfo)

**Comment by kerwinso** [comment]
For `col23622` specifically, Ross manually fixed it.

**Comment by reedstrm** [comment]
It's a config setting for the rhaptos print tool. Seems staging deploy has the same value set as production.

**Comment by karenc** [comment]
The pull request for setting the rhaptos print print host url has been merged in #383.
