### ISSUE TITLE
Add nvm installation for acquiring the latest stable nodejs

### ISSUE THREAD

**Issue by pumazi** [Connexions/cnx-deploy#43]
## Summary

Install [nvm](https://github.com/creationix/nvm) on Debian based systems (Homebrew can remain in use for Darwin). This can then be used in with ansible's npm module (see the `executable` parameter). It should mean we can stop writing to the `PATH` environment variable.

Currently we install a known version of nodejs to `/tmp` and use that to build. Using nvm might give us a bit more flexibility and a more sustainable solution, because it will hopefully allow the version to be kept up-to-date.

## Environment

all on Debian based systems

**Comment by pumazi** [comment]
See also https://openstax.slack.com/archives/cte/p1461881015001336, where phil mentions a similar pull request: https://github.com/openstax/tutor-deployment/pull/229

**Comment by philschatz** [comment]
any updates on this feature? Could it be added to tutor-deployment? I had trouble installing it in tutor-deployment but maybe the debian package would fix the problem I ran into?

**Comment by pumazi** [comment]
No longer needed on account of webview being built prior to deployment. 🎉
