### ISSUE TITLE
Allow the Zope application to connect to the PostgreSQL server

### ISSUE THREAD

**Issue by pumazi** [Connexions/cnx-deploy#5]
## Summary

The Zope application cannot connect to the remote PostgreSQL database. The PostgreSQL server is currently setup to only allow for local connections. Thus an external connection from Zope fails.

A task needs to be created to configure PostgreSQL to allow configured hosts to connect to the database.

## Environment

cte-dev within cte-legacy-dev

**Comment by karenc** [comment]
https://github.com/Connexions/cnx-deploy/pull/36 probably fixed this.
