### ISSUE TITLE
press was not deployed to qa.cnx.org

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-deploy#587]
## Summary
Ross confirmed that cnx-press is not up on qa.cnx.org even though I deployed the latest version of `master` via Rundeck there last night (https://bastion2.cnx.org/project/Dev_cnx-deploy/execution/show/35186).

## Environment
> What is the name of the environment you are using (i.e `environments/___`)? What is the OS name and version that you are deploying on? For example, `local on Debian 8.3`.

qa via Rundeck

**Comment by pumazi** [comment]
From the rundeck logs:
```
PLAY [install press] ***********************************************************
--
15:14:20 |   |   | skipping: no hosts matched
```

**Comment by pumazi** [comment]
`/var/cnx-deploy` contains manual changes again.

**Comment by kerwinso** [comment]
Per Ross, press is now running on qa.

```
reedstrm@qa00:~$ sudo supervisorctl status press:press-0
press:press-0                    RUNNING   pid 17985, uptime 1:21:28
```

**Comment by kerwinso** [comment]
```
kerwin@qa00:~$ sudo supervisorctl status press:press-0
press:press-0                    RUNNING   pid 17259, uptime 17:56:01
```
