### ISSUE TITLE
code only changes do not restart press

### ISSUE THREAD

**Issue by pumazi** [Connexions/cnx-deploy#596]
## Summary

The deployment of code only changes for press does not cause the press procs to restart.

We do have it restarting working when there are dependencies added or configuration changes.

Tied to changes deployed and tested then reported to https://github.com/Connexions/nebuchadnezzar/issues/42

## Environment

all

**Comment by kerwinso** [comment]
@pumazi Thanks for logging this. Who would be the best person to work on this fix, should I submit a DevOps request?

**Comment by pumazi** [comment]
@kerwinso, that sounds good. It's likely we can crib the solution from one of the other deployments since they also deploy from git, which we haven't done for our things up until now.

**Comment by kerwinso** [comment]
https://trello.com/c/Ca7t90qB/117-cnx-deploy-code-only-changes-do-not-restart-press
