### ISSUE TITLE
postgresql doesn't start on server start

### ISSUE THREAD

**Issue by reedstrm** [Connexions/cnx-deploy#6]
the postgresql service is not started on restart of server. This error shows up in /var/log/boot.log

Error: could not exec /usr/lib/postgresql/9.4/bin/pg_ctl /usr/lib/postgresql/9.4/bin/pg_ctl start -D /var/lib/postgresql/9.4/main -l /var/log/postgresql/postgresql-9.4-main.log -s -o  -c config_file="/etc/postgresql/9.4/main/postgresql.conf" : 
- Starting PostgreSQL 9.4 database server                                                                    [fail]

Manual start succeeds

The command above does in fact fail if copy and pasted at the bash prompt. Everything past the -o (the -c and its arguments) needs to be quoted together. Searching for a bug in ubuntu or debian upstream

**Comment by pumazi** [comment]
By the way, we are using pgdg (http://apt.postgresql.org) on this machine.

**Comment by DarkPrinceFrost** [comment]
I _believe_ this issue has been fixed with the use of `systemctl`
