### ISSUE TITLE
Varnish configs should be split

### ISSUE THREAD

**Issue by reedstrm** [Connexions/cnx-deploy#608]
## Problem

We have varnish deployed (on production) to 3 servers - one for legacy, two load-balanced for archive.
All three instances run the same, overly complex, config. This should be split at least in two

The "gotcha" then is to decide what to do about a single-server install (like qa, devb, contentXX)
One varnish w/ a combined config? (giving 3 configs) or 2 varnish instances? I think I vote for the second.

**Comment by reedstrm** [comment]
I've done further work on this, since it was necessary to make neb work on multi-host production-like deployment. We now have the legacy varnish split out and pared down. Working on cleaning up the non-legacy config now, since it is throwing errors as well.

**Comment by kerwinso** [comment]
@reedstrm Was this addressed by https://github.com/Connexions/cnx-deploy/pull/630?
