### ISSUE TITLE
SEO Page load times: Optimizations from Google PageSpeed Insights Part 1

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-deploy#720]
# Description

Google PageSpeed Insights (https://developers.google.com/speed/pagespeed/insights/?url=cnx.org&tab=desktop) reports cnx.org is fast but low on optimizations. Go to Desktop (not mobile) -> Show Optimizations. Implementing more optimizations would further speed up our page load times.

# Impact
* **Severity**: [ ] High [x] Medium  [ ] Low
* **Frequency of Occurence**: [x] High [ ] Medium  [ ] Low

# Acceptance (these could be split into multiple cards)
- Enable gzip compression (probably in nginx or haproxy) for cnx archive json, cnx.org scripts and images and openstax.org api responses (list of books).
- Enable gzip compression in cloudfront settings (for whichever cloudfront distribution is used by openstax.org for the book covers).
- Enable browser caching headers for /images (OpenStax/Rice logos etc), cloudfront svgs (book covers) and /scripts/require.js (https://trello.com/c/jPHr1INO is probably related to this).
- DEFER TO FUTURE RELEASE: Optimize images so they are smaller (see guide in above page).

# Next Steps for User
_If the card is accepted or rejected, what does user need to know now?_
If the card is rejected, performance would remain the same.

# PRs
openstax/oscms-deployment#66
Connexions/cnx-archive#580
Connexions/webview#1817
 Connexions/cnx-deploy#728
 Connexions/cnx-deploy#730
 Connexions/cnx-deploy#731

# Test Plan
- If you look in the network tab, all svgs (except book covers, those have not been done because https://trello.com/c/h9d3d4lt has not been done), html, js, json, xml, sourcemaps (.map) files on CNX should now have come with a `Content-Encoding: gzip` header. Loading the whole site should require less megabytes (I'm seeing about 1 megabyte less) than before and be faster, especially on slower connections.
- All requests to archive should now come with a Cache-Control header.
- If during any testing you improperly get stale content (More than ~2 minutes old. For example, if you publish a new version of something and the content does not update within 2 minutes.) from any archive url, it may be caused by this card and may cause it to fail testing.

**Comment by Dantemss** [comment]
Linked PR: https://github.com/openstax/oscms-deployment/pull/66 (can't add this directly because it's in another organization)

**Comment by kerwinso** [comment]
Per Dante, the test plan covers only the work that's going in to 8/27 release.

**Comment by kerwinso** [comment]
## QA Test Plan and Comments
- [ ] If you look in the network tab, all svgs (except book covers, those have not been done because trello.com/c/h9d3d4lt has not been done), html, js, json, xml, sourcemaps (.map) files on CNX should now have come with a Content-Encoding: gzip header. Loading the whole site should require less megabytes (I'm seeing about 1 megabyte less) than before and be faster, especially on slower connections. 
	- does this apply to analytics.js @Dantemss ?

- [ ] All requests to archive should now come with a Cache-Control header.
	- this doesn't apply to 301 and 302 redirects, right @Dantemss ?

- [ ] If during any testing you improperly get stale content (More than ~2 minutes old. For example, if you publish a new version of something and the content does not update within 2 minutes.) from any archive url, it may be caused by this card and may cause it to fail testing.
	- where do I check for this @Dantemss ?

**Comment by Dantemss** [comment]
1. I can't control Google :P but I do seem to get analytics.js gzipped, it's just that the content-encoding header is all lower-case for Google for some reason
2. Ah yes, I don't think I set headers on the redirects... But it can be done. Next release maybe.
3. This is only if you observe any odd caching behavior while testing other stuff. Don't test for this specifically.

**Comment by kerwinso** [comment]
Looks good on staging. Couldn't really find html or svg files to check in Network activity, but non-redirect js and json files that we serve match the test plan.

**Comment by kerwinso** [comment]
@kerwinso Might want to look at this again when we deploy fixes to cnx-archive.
