### ISSUE TITLE
Import of the Slim Dump results in empty tables

### ISSUE THREAD

**Issue by pumazi** [Connexions/cnx-deploy#737]
## Summary

When the slim dump is imported or loaded into the database the results are a fully schematized database but without any data. The size of the dump file would indicate that it does indeed have content in it, but nothing is actually put into the tables.

See also [How To: Get a Slim Database Dump](https://github.com/Connexions/devops/wiki/How-To%3A-Get-a-Slim-Database-Dump) & [Docker-compose usage: Using the slim dump](https://github.com/Connexions/cnx-press/wiki/Docker-Compose-usage#using-the-slim-dump)

## Environment

None

**Comment by reedstrm** [comment]
Seems the system that the slim dumps are created on had run out of space, and failed to create complete dumps. Devops has addressed this and triggered a fresh slim dump.

**Comment by dtwilliamson** [comment]
It has completed and seems to be an appropriate size.

**Comment by pumazi** [comment]
Great work debugging and resolving this guys! Thank you

**Comment by pumazi** [comment]
I've verified this is resolved.
