### ISSUE TITLE
varnish service startup hack wrong on 16.04.1

### ISSUE THREAD

**Issue by reedstrm** [Connexions/cnx-deploy#74]
## Summary

The regex replace inside  /etc/systemd/system/multi-user.target.wants/varnish.service
in the task  "configure varnish runtime (systemd config)"
fails on an ubuntu 16.04.1 target , since it has a slightly diff. looking ExecStart line. (Fraid I didn't save it, will add later)

## Environment

all on Ubuntu 16.04

**Comment by pumazi** [comment]
Resolved in f3139658a8cc60f638e278d68b1145983c9d1685
