### ISSUE TITLE
varnishlog doesn't specify the instance name "varnish"

### ISSUE THREAD

**Issue by dtwilliamson** [Connexions/cnx-deploy#778]
## Summary

When the varnish config was split, instance names were used to separate the parts. The instance name argument was added to `varnishd` and `varnishncsa`, but not to `varnishlog`.

## Detail

This causes `varnishlog` to output errors like this from `sudo systemctl status varnishncsa varnishlog`:

`Sep 07 12:48:10 staging01 varnishlog[10520]: Can't open log - retrying for 5 seconds`

instead of doing the logging that it should be.

The systemd file for varnishlog, `/etc/systemd/system/varnishlog.service`, needs to have `-n varnish` at the end of the `ExecStart` line.

NOTE: Ideally, however, both `varnishncsa` and `varnishlog` should have `DAEMON_OPTS` set in their `/etc/defaults/` files as `varnish` itself has and their systemd service files should use `$DAEMON_OPTS` as their only argument in their `ExecStart` lines. These services already have their appropriate `EnvironmentFile` defined in their service files. Note also that the argument lists for each of the three services is different.

`cnx-deploy` needs to be updated where this instance name is added to the other components with this change.

`varnishlog` uses the host name as the default instance name if one isn't specified. As a result, as part of this issue, the directory `/var/lib/varnish/staging01/`, for example, needs to be removed (if it exists) since it won't be used when the instance name is specified as above and isn't being properly used now.

## Acceptance criteria

`/var/log/varnish/varnish.log` will have useful contents and `sudo varnishlog -d -r /var/log/varnish/varnish.log` will produce outout. Also, no error message like the one above.

**Comment by dtwilliamson** [comment]
It looks like this issue also applies to the `legacy-varnish` instance.

**Comment by edwoodward** [comment]
https://github.com/Connexions/cnx-deploy/pull/830

**Comment by brittweinstein** [comment]
@dtwilliamson after Ross's review, please review and merge.

**Comment by openstaxalina** [comment]
Per @reedstrm, this passes on staging.cnx.org.
